# Generated by Django 5.0.3 on 2024-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('fiction', 'fiction'), ('nobels', 'nobels'), ('calculation', 'calculation'), ('computer', 'computer'), ('others', 'others')], default='others', max_length=20)),
                ('shelf', models.CharField(max_length=5)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='login_detail',
        ),
    ]
