# Generated by Django 5.0.3 on 2024-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_student_delete_login_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nobels', 'Novels'), ('calculation', 'Calculations'), ('computer', 'Computer'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
